// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "turnover"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  TWeekPropsRecvInfoQueryPage queryAnchorWeekPropsRecieve(i64 uid, TAppId appid, i64 startTime, i64 endTime, i32 page, i32 pagesize,  propIds,  playTypes)")
  fmt.Fprintln(os.Stderr, "  TWeekPropsRecvInfoQueryPage queryChannelWeekPropsRecieve(i64 sid, TAppId appid, i64 startTime, i64 endTime, i32 page, i32 pagesize, i64 usedUid)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := turnover.NewTPropsServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "queryAnchorWeekPropsRecieve":
    if flag.NArg() - 1 != 8 {
      fmt.Fprintln(os.Stderr, "QueryAnchorWeekPropsRecieve requires 8 args")
      flag.Usage()
    }
    argvalue0, err86 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err86 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err := (strconv.Atoi(flag.Arg(2)))
    if err != nil {
      Usage()
     return
    }
    argvalue1 := turnover.TAppId(tmp1)
    value1 := argvalue1
    argvalue2, err87 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err87 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    argvalue3, err88 := (strconv.ParseInt(flag.Arg(4), 10, 64))
    if err88 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    tmp4, err89 := (strconv.Atoi(flag.Arg(5)))
    if err89 != nil {
      Usage()
      return
    }
    argvalue4 := int32(tmp4)
    value4 := argvalue4
    tmp5, err90 := (strconv.Atoi(flag.Arg(6)))
    if err90 != nil {
      Usage()
      return
    }
    argvalue5 := int32(tmp5)
    value5 := argvalue5
    arg91 := flag.Arg(7)
    mbTrans92 := thrift.NewTMemoryBufferLen(len(arg91))
    defer mbTrans92.Close()
    _, err93 := mbTrans92.WriteString(arg91)
    if err93 != nil { 
      Usage()
      return
    }
    factory94 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt95 := factory94.GetProtocol(mbTrans92)
    containerStruct6 := turnover.NewTPropsServiceQueryAnchorWeekPropsRecieveArgs()
    err96 := containerStruct6.ReadField7(jsProt95)
    if err96 != nil {
      Usage()
      return
    }
    argvalue6 := containerStruct6.PropIds
    value6 := argvalue6
    arg97 := flag.Arg(8)
    mbTrans98 := thrift.NewTMemoryBufferLen(len(arg97))
    defer mbTrans98.Close()
    _, err99 := mbTrans98.WriteString(arg97)
    if err99 != nil { 
      Usage()
      return
    }
    factory100 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt101 := factory100.GetProtocol(mbTrans98)
    containerStruct7 := turnover.NewTPropsServiceQueryAnchorWeekPropsRecieveArgs()
    err102 := containerStruct7.ReadField8(jsProt101)
    if err102 != nil {
      Usage()
      return
    }
    argvalue7 := containerStruct7.PlayTypes
    value7 := argvalue7
    fmt.Print(client.QueryAnchorWeekPropsRecieve(context.Background(), value0, value1, value2, value3, value4, value5, value6, value7))
    fmt.Print("\n")
    break
  case "queryChannelWeekPropsRecieve":
    if flag.NArg() - 1 != 7 {
      fmt.Fprintln(os.Stderr, "QueryChannelWeekPropsRecieve requires 7 args")
      flag.Usage()
    }
    argvalue0, err103 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err103 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err := (strconv.Atoi(flag.Arg(2)))
    if err != nil {
      Usage()
     return
    }
    argvalue1 := turnover.TAppId(tmp1)
    value1 := argvalue1
    argvalue2, err104 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err104 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    argvalue3, err105 := (strconv.ParseInt(flag.Arg(4), 10, 64))
    if err105 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    tmp4, err106 := (strconv.Atoi(flag.Arg(5)))
    if err106 != nil {
      Usage()
      return
    }
    argvalue4 := int32(tmp4)
    value4 := argvalue4
    tmp5, err107 := (strconv.Atoi(flag.Arg(6)))
    if err107 != nil {
      Usage()
      return
    }
    argvalue5 := int32(tmp5)
    value5 := argvalue5
    argvalue6, err108 := (strconv.ParseInt(flag.Arg(7), 10, 64))
    if err108 != nil {
      Usage()
      return
    }
    value6 := argvalue6
    fmt.Print(client.QueryChannelWeekPropsRecieve(context.Background(), value0, value1, value2, value3, value4, value5, value6))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
