// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "tunnel"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  i32 unicastByUid(i64 appid, i32 uid, string msg)")
  fmt.Fprintln(os.Stderr, "  i32 unicastByUidEx(i64 appid, i32 uid, string msg, i32 msg_type)")
  fmt.Fprintln(os.Stderr, "  i32 unicastToRoomByUidEx(i64 appid, i32 sid, i32 uid, string msg, i32 msg_type)")
  fmt.Fprintln(os.Stderr, "  i32 broadcastBySid(i64 appid, i32 sid, string msg)")
  fmt.Fprintln(os.Stderr, "  i32 broadcastBySidEx(i64 appid, i32 sid, i32 msg_type, string msg)")
  fmt.Fprintln(os.Stderr, "  i32 onOfficialMike(i64 uid, i32 sid, string msg)")
  fmt.Fprintln(os.Stderr, "  i32 offOfficialMike(i64 uid, i32 sid, string msg)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := tunnel.NewTunnelClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "unicastByUid":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "UnicastByUid requires 3 args")
      flag.Usage()
    }
    argvalue0, err16 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err16 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err17 := (strconv.Atoi(flag.Arg(2)))
    if err17 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.UnicastByUid(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "unicastByUidEx":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "UnicastByUidEx requires 4 args")
      flag.Usage()
    }
    argvalue0, err19 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err19 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err20 := (strconv.Atoi(flag.Arg(2)))
    if err20 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    tmp3, err22 := (strconv.Atoi(flag.Arg(4)))
    if err22 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    fmt.Print(client.UnicastByUidEx(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "unicastToRoomByUidEx":
    if flag.NArg() - 1 != 5 {
      fmt.Fprintln(os.Stderr, "UnicastToRoomByUidEx requires 5 args")
      flag.Usage()
    }
    argvalue0, err23 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err23 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err24 := (strconv.Atoi(flag.Arg(2)))
    if err24 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err25 := (strconv.Atoi(flag.Arg(3)))
    if err25 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    tmp4, err27 := (strconv.Atoi(flag.Arg(5)))
    if err27 != nil {
      Usage()
      return
    }
    argvalue4 := int32(tmp4)
    value4 := argvalue4
    fmt.Print(client.UnicastToRoomByUidEx(context.Background(), value0, value1, value2, value3, value4))
    fmt.Print("\n")
    break
  case "broadcastBySid":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "BroadcastBySid requires 3 args")
      flag.Usage()
    }
    argvalue0, err28 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err28 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err29 := (strconv.Atoi(flag.Arg(2)))
    if err29 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.BroadcastBySid(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "broadcastBySidEx":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "BroadcastBySidEx requires 4 args")
      flag.Usage()
    }
    argvalue0, err31 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err31 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err32 := (strconv.Atoi(flag.Arg(2)))
    if err32 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err33 := (strconv.Atoi(flag.Arg(3)))
    if err33 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.BroadcastBySidEx(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "onOfficialMike":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "OnOfficialMike requires 3 args")
      flag.Usage()
    }
    argvalue0, err35 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err35 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err36 := (strconv.Atoi(flag.Arg(2)))
    if err36 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.OnOfficialMike(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "offOfficialMike":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "OffOfficialMike requires 3 args")
      flag.Usage()
    }
    argvalue0, err38 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err38 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err39 := (strconv.Atoi(flag.Arg(2)))
    if err39 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.OffOfficialMike(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
