// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
	"common"
        "callrecord"
)

var _ = common.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  ComRet finishNewUserRandomCallTask(i64 toUserId, bool isFinish, i32 flowerNum)")
  fmt.Fprintln(os.Stderr, "  ComRet addMissedCall(i64 fromUserId, i64 toUserId, i32 isFriendCall, string applyId)")
  fmt.Fprintln(os.Stderr, "  ComRet addCallRecordByCCServer(i64 beginTime, string callId, i64 endTime, string flowerCounts, i64 toUserId, i32 callType, i64 fromUserId, string netType)")
  fmt.Fprintln(os.Stderr, "  ComRet addUserFlowerByCall(string callId, i64 fromUserId, i64 toUserId, i32 type)")
  fmt.Fprintln(os.Stderr, "  GetUserRoomRet getUserRoom(i64 userId, i64 roomId, i32 roomType)")
  fmt.Fprintln(os.Stderr, "  ComRet updateRoomTopic(i64 userId, i64 roomId, i32 roomType, string newTopic)")
  fmt.Fprintln(os.Stderr, "  QueryMyRoomWhiteListRet queryMyRoomWhiteList()")
  fmt.Fprintln(os.Stderr, "  i32 ping()")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := callrecord.NewCallRecordServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "finishNewUserRandomCallTask":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "FinishNewUserRandomCallTask requires 3 args")
      flag.Usage()
    }
    argvalue0, err16 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err16 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2) == "true"
    value1 := argvalue1
    tmp2, err18 := (strconv.Atoi(flag.Arg(3)))
    if err18 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.FinishNewUserRandomCallTask(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "addMissedCall":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "AddMissedCall requires 4 args")
      flag.Usage()
    }
    argvalue0, err19 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err19 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err20 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err20 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err21 := (strconv.Atoi(flag.Arg(3)))
    if err21 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.AddMissedCall(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "addCallRecordByCCServer":
    if flag.NArg() - 1 != 8 {
      fmt.Fprintln(os.Stderr, "AddCallRecordByCCServer requires 8 args")
      flag.Usage()
    }
    argvalue0, err23 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err23 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2, err25 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err25 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    argvalue4, err27 := (strconv.ParseInt(flag.Arg(5), 10, 64))
    if err27 != nil {
      Usage()
      return
    }
    value4 := argvalue4
    tmp5, err28 := (strconv.Atoi(flag.Arg(6)))
    if err28 != nil {
      Usage()
      return
    }
    argvalue5 := int32(tmp5)
    value5 := argvalue5
    argvalue6, err29 := (strconv.ParseInt(flag.Arg(7), 10, 64))
    if err29 != nil {
      Usage()
      return
    }
    value6 := argvalue6
    argvalue7 := flag.Arg(8)
    value7 := argvalue7
    fmt.Print(client.AddCallRecordByCCServer(context.Background(), value0, value1, value2, value3, value4, value5, value6, value7))
    fmt.Print("\n")
    break
  case "addUserFlowerByCall":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "AddUserFlowerByCall requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1, err32 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err32 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    argvalue2, err33 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err33 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    tmp3, err34 := (strconv.Atoi(flag.Arg(4)))
    if err34 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    fmt.Print(client.AddUserFlowerByCall(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "getUserRoom":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetUserRoom requires 3 args")
      flag.Usage()
    }
    argvalue0, err35 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err35 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err36 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err36 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err37 := (strconv.Atoi(flag.Arg(3)))
    if err37 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.GetUserRoom(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "updateRoomTopic":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "UpdateRoomTopic requires 4 args")
      flag.Usage()
    }
    argvalue0, err38 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err38 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err39 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err39 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err40 := (strconv.Atoi(flag.Arg(3)))
    if err40 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.UpdateRoomTopic(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "queryMyRoomWhiteList":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "QueryMyRoomWhiteList requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.QueryMyRoomWhiteList(context.Background()))
    fmt.Print("\n")
    break
  case "ping":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "Ping requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.Ping(context.Background()))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
