// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "turnover"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "   queryRevenueRecord(i64 sid, i32 appid, string timeGreaterThan, string timeLessThan, i32 revenueUserType, i32 page, i32 pagesize, i64 anchorUid)")
  fmt.Fprintln(os.Stderr, "   queryUserMonthSettleApply(i64 uid, i64 timeGreaterThan, i64 timeLessThan, i32 appid, i32 page, i32 pagesize)")
  fmt.Fprintln(os.Stderr, "  TChannelAccount getChannelAccountByUidAndType(i64 uid, i64 sid, TAppId appid, TCurrencyType currencyType)")
  fmt.Fprintln(os.Stderr, "  TQueryPageInfo queryRevenueRecordPaging(i64 uid, TAppId appid, i32 pagesize, i32 page, TUserType revenueUserType, i64 startDate, i64 endDate, i64 anchorUid, i64 sid, TRevenueSrcType srcType)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := turnover.NewTCurrencyServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "queryRevenueRecord":
    if flag.NArg() - 1 != 8 {
      fmt.Fprintln(os.Stderr, "QueryRevenueRecord requires 8 args")
      flag.Usage()
    }
    argvalue0, err28 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err28 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err29 := (strconv.Atoi(flag.Arg(2)))
    if err29 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    tmp4, err32 := (strconv.Atoi(flag.Arg(5)))
    if err32 != nil {
      Usage()
      return
    }
    argvalue4 := int32(tmp4)
    value4 := argvalue4
    tmp5, err33 := (strconv.Atoi(flag.Arg(6)))
    if err33 != nil {
      Usage()
      return
    }
    argvalue5 := int32(tmp5)
    value5 := argvalue5
    tmp6, err34 := (strconv.Atoi(flag.Arg(7)))
    if err34 != nil {
      Usage()
      return
    }
    argvalue6 := int32(tmp6)
    value6 := argvalue6
    argvalue7, err35 := (strconv.ParseInt(flag.Arg(8), 10, 64))
    if err35 != nil {
      Usage()
      return
    }
    value7 := argvalue7
    fmt.Print(client.QueryRevenueRecord(context.Background(), value0, value1, value2, value3, value4, value5, value6, value7))
    fmt.Print("\n")
    break
  case "queryUserMonthSettleApply":
    if flag.NArg() - 1 != 6 {
      fmt.Fprintln(os.Stderr, "QueryUserMonthSettleApply requires 6 args")
      flag.Usage()
    }
    argvalue0, err36 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err36 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err37 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err37 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    argvalue2, err38 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err38 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    tmp3, err39 := (strconv.Atoi(flag.Arg(4)))
    if err39 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    tmp4, err40 := (strconv.Atoi(flag.Arg(5)))
    if err40 != nil {
      Usage()
      return
    }
    argvalue4 := int32(tmp4)
    value4 := argvalue4
    tmp5, err41 := (strconv.Atoi(flag.Arg(6)))
    if err41 != nil {
      Usage()
      return
    }
    argvalue5 := int32(tmp5)
    value5 := argvalue5
    fmt.Print(client.QueryUserMonthSettleApply(context.Background(), value0, value1, value2, value3, value4, value5))
    fmt.Print("\n")
    break
  case "getChannelAccountByUidAndType":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "GetChannelAccountByUidAndType requires 4 args")
      flag.Usage()
    }
    argvalue0, err42 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err42 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err43 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err43 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err := (strconv.Atoi(flag.Arg(3)))
    if err != nil {
      Usage()
     return
    }
    argvalue2 := turnover.TAppId(tmp2)
    value2 := argvalue2
    tmp3, err := (strconv.Atoi(flag.Arg(4)))
    if err != nil {
      Usage()
     return
    }
    argvalue3 := turnover.TCurrencyType(tmp3)
    value3 := argvalue3
    fmt.Print(client.GetChannelAccountByUidAndType(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "queryRevenueRecordPaging":
    if flag.NArg() - 1 != 10 {
      fmt.Fprintln(os.Stderr, "QueryRevenueRecordPaging requires 10 args")
      flag.Usage()
    }
    argvalue0, err44 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err44 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err := (strconv.Atoi(flag.Arg(2)))
    if err != nil {
      Usage()
     return
    }
    argvalue1 := turnover.TAppId(tmp1)
    value1 := argvalue1
    tmp2, err45 := (strconv.Atoi(flag.Arg(3)))
    if err45 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    tmp3, err46 := (strconv.Atoi(flag.Arg(4)))
    if err46 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    tmp4, err := (strconv.Atoi(flag.Arg(5)))
    if err != nil {
      Usage()
     return
    }
    argvalue4 := turnover.TUserType(tmp4)
    value4 := argvalue4
    argvalue5, err47 := (strconv.ParseInt(flag.Arg(6), 10, 64))
    if err47 != nil {
      Usage()
      return
    }
    value5 := argvalue5
    argvalue6, err48 := (strconv.ParseInt(flag.Arg(7), 10, 64))
    if err48 != nil {
      Usage()
      return
    }
    value6 := argvalue6
    argvalue7, err49 := (strconv.ParseInt(flag.Arg(8), 10, 64))
    if err49 != nil {
      Usage()
      return
    }
    value7 := argvalue7
    argvalue8, err50 := (strconv.ParseInt(flag.Arg(9), 10, 64))
    if err50 != nil {
      Usage()
      return
    }
    value8 := argvalue8
    tmp9, err := (strconv.Atoi(flag.Arg(10)))
    if err != nil {
      Usage()
     return
    }
    argvalue9 := turnover.TRevenueSrcType(tmp9)
    value9 := argvalue9
    fmt.Print(client.QueryRevenueRecordPaging(context.Background(), value0, value1, value2, value3, value4, value5, value6, value7, value8, value9))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
